server:
  port: ${PORT:8080}
  servlet.session.tracking-modes: cookie

spring:
  datasource:
    url: jdbc:h2:~/h2db/zaster;AUTO_SERVER=TRUE
    username: sa
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
  mustache:
    check-template-location: false

logging:
  level:
    org.atmosphere: warn
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: debug
    org.springframework.security: info

vaadin:
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - de.spicom.zaster
